-- Motif: patterns table schema for Supabase (Postgres + pgvector).
-- Run this once in the Supabase SQL Editor (Database -> SQL Editor -> New query).
-- Safe to re-run: every statement is idempotent (if not exists / or replace).
--
-- psycopg gotcha: when inserting/querying the `embedding` column from
-- Python, cast the parameter explicitly, e.g. `%s::vector`. Without numpy
-- installed, pgvector's register_vector() doesn't reliably adapt a plain
-- Python list to `vector`, and it silently falls back to a
-- `double precision[]` array, which has no <=> operator against `vector`.
-- Applies anywhere embeddings are bound as query parameters, including
-- pipeline/store_patterns.py.

create extension if not exists vector;

create table if not exists patterns (
    id bigint generated always as identity primary key,
    created_at timestamptz not null default now(),

    -- source video metadata, fetched by pipeline/youtube_fetcher.py
    video_url text not null unique,
    title text not null,
    views bigint not null,
    likes bigint,
    comment_count bigint,
    duration_seconds numeric not null,
    published_at timestamptz,

    -- structural pattern fields, matching backend/src/models/schemas.py::Pattern
    niche text not null,
    platform text not null check (platform in ('tiktok', 'reels', 'youtube_shorts')),
    hook_style text not null,
    hook_text text not null,
    hook_delivery_seconds numeric not null,
    visual_format text not null,
    scene_change_frequency text not null,
    on_screen_text boolean not null,
    camera_style text not null,
    reveal_order text not null,
    payoff_seconds numeric not null,
    cta_type text not null,
    -- null, not 0, when no CTA phrase was detected in the transcript -
    -- see the note in pipeline/youtube_fetcher.py::compute_structural_signals.
    cta_placement_percent numeric,
    pacing text not null,
    emotional_trigger text not null,
    success_factors text[] not null,

    -- embedding, generated by backend/src/services/embeddings.py
    -- (OpenAI text-embedding-3-small -> 1536 dimensions)
    document text not null,
    embedding vector(1536) not null,

    -- Separate from document/embedding on purpose: document is a
    -- structural-pattern description (hook style, pacing, camera work...)
    -- for retrieval matching in brief_generator.py. topic_summary is a
    -- plain "what is this video actually about" sentence with no
    -- structural language at all - confirmed live that comparing a topic
    -- description against embeddings of the structural document scores
    -- far too low even for genuinely correct niche matches, because
    -- they're different kinds of text. Used by pipeline/classify_niche.py.
    topic_summary text,
    topic_embedding vector(1536)
);

-- Speeds up get_patterns_by_niche_platform().
create index if not exists patterns_niche_platform_idx
    on patterns (niche, platform);

-- Speeds up query_similar_patterns() cosine-distance search.
-- Uses HNSW (pgvector >= 0.5.0, default on current Supabase projects).
-- If your project's pgvector predates 0.5.0, drop this and use:
--   create index on patterns using ivfflat (embedding vector_cosine_ops) with (lists = 100);
-- instead (ivfflat needs rows already present to build well).
create index if not exists patterns_embedding_idx
    on patterns using hnsw (embedding vector_cosine_ops);
