# Embeds a Pattern and stores it (document + embedding + metadata) in the
# shared Supabase "patterns" table (see backend/sql/schema.sql).
#
# Standalone by design: the pipeline shares the database with backend/ but
# imports nothing from backend/src/, so it owns its own OpenAI client and
# psycopg connection rather than reusing embeddings.py / retrieval.py.

import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from openai import OpenAI

# See the same note in youtube_fetcher.py - load_dotenv() with no args
# never finds backend/.env from here.
load_dotenv(Path(__file__).resolve().parent.parent / "backend" / ".env")

client = OpenAI()

# Must match backend/src/services/embeddings.py, or stored vectors and query
# vectors live in different spaces and cosine distance becomes meaningless.
EMBEDDING_MODEL = "text-embedding-3-small"

# Every column the insert supplies. id, created_at, document and embedding
# are excluded: the first two are generated by Postgres, the last two by this
# module.
_PATTERN_COLUMNS = (
    "video_url",
    "title",
    "views",
    "likes",
    "comment_count",
    "duration_seconds",
    "published_at",
    "niche",
    "platform",
    "hook_style",
    "hook_text",
    "hook_delivery_seconds",
    "visual_format",
    "scene_change_frequency",
    "on_screen_text",
    "camera_style",
    "reveal_order",
    "payoff_seconds",
    "cta_type",
    "cta_placement_percent",
    "pacing",
    "emotional_trigger",
    "success_factors",
)


def build_document(pattern: dict) -> str:
    """
    Render a pattern as the prose that gets embedded.

    This is what vector search actually matches against, so it is written as
    natural language rather than a field dump: retrieval.query_similar_patterns
    embeds a plain-English description of desired content, and the two have to
    live in the same space to be comparable.

    Args:
        pattern: A dict matching the Pattern schema.

    Returns:
        The document text to embed and store.
    """
    factors = pattern.get("success_factors") or []
    return " ".join(
        part
        for part in [
            f"A {pattern['niche']} video on {pattern['platform']}.",
            f"The hook is {pattern['hook_style']}, delivered at"
            f" {pattern['hook_delivery_seconds']} seconds: \"{pattern['hook_text']}\".",
            f"Visual format is {pattern['visual_format']} with"
            f" {pattern['camera_style']} camera work and"
            f" {pattern['scene_change_frequency']} scene changes.",
            "It uses on-screen text."
            if pattern.get("on_screen_text")
            else "It has no on-screen text.",
            f"Information is revealed {pattern['reveal_order']}, with the payoff"
            f" at {pattern['payoff_seconds']} seconds.",
            f"Pacing is {pattern['pacing']}.",
            (
                f"The call to action is {pattern['cta_type']}, placed"
                f" {pattern['cta_placement_percent']}% through."
                if pattern.get("cta_placement_percent") is not None
                # None means no CTA phrase was detected in the transcript,
                # not "placed at 0%" - see youtube_fetcher.py.
                else f"The call to action is {pattern['cta_type']};"
                " no verbal CTA timing was detected."
            ),
            f"The emotional trigger is {pattern['emotional_trigger']}.",
            f"It works because: {'; '.join(factors)}." if factors else "",
        ]
        if part
    )


def generate_embedding(text: str) -> list[float]:
    """
    Embed the given text with OpenAI's text-embedding-3-small.

    Mirrors backend/src/services/embeddings.py rather than importing it, to
    keep the pipeline runnable on its own.

    Args:
        text: The input text to embed.

    Returns:
        A 1536-dimension embedding vector.
    """
    response = client.embeddings.create(model=EMBEDDING_MODEL, input=text)
    return response.data[0].embedding


def store_pattern(pattern: dict) -> None:
    """
    Generate an embedding for the pattern and upsert it into Supabase, with
    all pattern fields persisted as columns alongside the document text
    and embedding.

    Upsert, not insert: video_url is UNIQUE, so re-running build_library.py
    over the same URL list refreshes those rows instead of erroring.

    Args:
        pattern: A dict matching the Pattern schema, plus the video metadata
            keys from youtube_fetcher.fetch_video_metadata. May optionally
            include "topic_summary" (see classify_niche.generate_topic_summary)
            - if present, it's embedded and stored separately from
            document/embedding for pipeline.classify_niche.py to use.
            Nullable in the schema, so omitting it is fine.
    """
    missing = [c for c in _PATTERN_COLUMNS if c not in pattern]
    if missing:
        raise ValueError(f"Pattern is missing required fields: {missing}")

    document = build_document(pattern)
    embedding = generate_embedding(document)

    columns = list(_PATTERN_COLUMNS) + ["document", "embedding"]
    # The embedding placeholder is cast explicitly. Without numpy installed,
    # a plain Python list silently binds as double precision[] instead of
    # vector, which has no <=> operator - see the note atop schema.sql.
    placeholders = ["%s"] * len(_PATTERN_COLUMNS) + ["%s", "%s::vector"]
    values = [pattern[c] for c in _PATTERN_COLUMNS] + [document, embedding]

    topic_summary = pattern.get("topic_summary")
    if topic_summary:
        columns += ["topic_summary", "topic_embedding"]
        placeholders += ["%s", "%s::vector"]
        values += [topic_summary, generate_embedding(topic_summary)]

    updates = ", ".join(f"{c} = excluded.{c}" for c in columns[1:])

    with psycopg.connect(os.environ["DATABASE_URL"]) as conn:
        with conn.cursor() as cur:
            cur.execute(
                f"""
                insert into patterns ({', '.join(columns)})
                values ({', '.join(placeholders)})
                on conflict (video_url) do update set {updates}
                """,
                values,
            )
        conn.commit()
