import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '@clerk/react'
import Mesh from '../components/Mesh.jsx'
import Nav from '../components/Nav.jsx'
import Pills from '../components/Pills.jsx'
import BriefContent from '../components/BriefContent.jsx'
import { useBrief } from '../store.jsx'
import { generateBrief, DemoModeUnavailable } from '../api.js'

export default function Brief() {
  const { brief } = useBrief()
  const { getToken } = useAuth()
  const [state, setState] = useState({ status: 'loading', data: null, error: null })

  useEffect(() => {
    let cancelled = false
    setState({ status: 'loading', data: null, error: null })

    generateBrief(brief, getToken)
      .then((data) => {
        if (!cancelled) setState({ status: 'ready', data, error: null })
      })
      .catch((error) => {
        if (cancelled) return
        if (error instanceof DemoModeUnavailable) {
          setState({ status: 'demo', data: null, error })
        } else {
          setState({ status: 'error', data: null, error })
        }
      })

    return () => {
      cancelled = true
    }
    // Regenerate only when the campaign inputs actually change, not on
    // every render - getToken is a new function reference from useAuth()
    // on most renders, and isn't itself something that should retrigger
    // generation.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [brief.niche, brief.platform, brief.audience, brief.objectives, brief.tone])

  return (
    <>
      <Mesh />
      <Nav
        variant="app"
        links={[
          { label: 'Market', to: '/market' },
          { label: 'Brief', to: '/brief', on: true },
          { label: 'Inputs', to: '/inputs' }
        ]}
      />

      <div className="wrap" style={{ paddingTop: 34 }}>
        <Pills brief={brief} left />

        {state.status === 'loading' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card loadcard">
              <div className="dots" aria-hidden="true"><i /><i /><i /></div>
              <p className="lmsg" role="status">
                Reasoning over structural patterns from top-performing {brief.niche} content on {brief.platform}…
              </p>
              <p className="lsub">Usually takes 10&ndash;20 seconds.</p>
            </div>
          </div>
        )}

        {state.status === 'demo' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card" style={{ padding: '40px' }}>
              <p style={{ fontWeight: 510, fontSize: 15.5 }}>This is a preview, not a live brief</p>
              <p style={{ color: 'var(--ink-2)', marginTop: 8, fontSize: 13.5, maxWidth: '60ch' }}>
                {state.error.message}
              </p>
              <p style={{ marginTop: 20 }}>
                <Link className="btn-primary" to="/signup">Create an account →</Link>
              </p>
            </div>
          </div>
        )}

        {state.status === 'error' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card" style={{ padding: '40px', background: 'var(--bad-bg)' }}>
              <p style={{ color: 'var(--bad)', fontWeight: 510, fontSize: 15.5 }}>Couldn&apos;t generate a brief</p>
              <p style={{ color: 'var(--ink-2)', marginTop: 8, fontSize: 13.5 }}>{state.error.message}</p>
              <p style={{ marginTop: 20 }}>
                <Link className="btn-dark" to="/vision">Back to creative direction →</Link>
              </p>
            </div>
          </div>
        )}

        {state.status === 'ready' && <BriefContent data={state.data} niche={brief.niche} />}
      </div>

      <div className="foot">
        <p>
          Generated by reasoning over structural patterns retrieved from top-performing {brief.niche} content on{' '}
          {brief.platform}, matched to this campaign&apos;s goal and audience.
        </p>
      </div>
    </>
  )
}
