import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '@clerk/react'
import Mesh from '../components/Mesh.jsx'
import Nav from '../components/Nav.jsx'
import Pills from '../components/Pills.jsx'
import BriefContent from '../components/BriefContent.jsx'
import { fetchSavedBrief, DemoModeUnavailable } from '../api.js'

/**
 * A past brief, fetched back by id from the dashboard's history list
 * (GET /api/briefs/{id}). Distinct from Brief.jsx (which generates a new
 * one from the live campaign context in store.jsx) because the context
 * here - niche/platform/audience/goal - has to come from the saved row
 * itself, not from useBrief()'s in-memory state, which reflects whatever
 * campaign is currently being built, not the one this brief was
 * generated for.
 */
export default function SavedBrief() {
  const { id } = useParams()
  const { getToken } = useAuth()
  const [state, setState] = useState({ status: 'loading', data: null, error: null })

  useEffect(() => {
    let cancelled = false
    setState({ status: 'loading', data: null, error: null })

    fetchSavedBrief(id, getToken)
      .then((data) => {
        if (cancelled) return
        setState(data ? { status: 'ready', data, error: null } : { status: 'missing', data: null, error: null })
      })
      .catch((error) => {
        if (cancelled) return
        if (error instanceof DemoModeUnavailable) {
          setState({ status: 'demo', data: null, error })
        } else {
          setState({ status: 'error', data: null, error })
        }
      })

    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id])

  return (
    <>
      <div className="no-print">
        <Mesh />
        <Nav variant="app" />
      </div>

      <div className="wrap" style={{ paddingTop: 34 }}>
        {state.status === 'loading' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card" style={{ padding: '48px 40px', textAlign: 'center' }}>
              <p style={{ fontSize: 15.5, color: 'var(--ink-2)' }}>Loading this brief…</p>
            </div>
          </div>
        )}

        {state.status === 'missing' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card" style={{ padding: '40px' }}>
              <p style={{ fontWeight: 510, fontSize: 15.5 }}>Couldn&apos;t find that brief</p>
              <p style={{ color: 'var(--ink-2)', marginTop: 8, fontSize: 13.5 }}>
                It may have been generated by a different account, or the link is wrong.
              </p>
            </div>
          </div>
        )}

        {state.status === 'demo' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card" style={{ padding: '40px' }}>
              <p style={{ fontWeight: 510, fontSize: 15.5 }}>Brief history isn&apos;t available in demo mode</p>
              <p style={{ color: 'var(--ink-2)', marginTop: 8, fontSize: 13.5, maxWidth: '60ch' }}>
                {state.error.message}
              </p>
            </div>
          </div>
        )}

        {state.status === 'error' && (
          <div className="sec" style={{ marginTop: 40 }}>
            <div className="card" style={{ padding: '40px', background: 'var(--bad-bg)' }}>
              <p style={{ color: 'var(--bad)', fontWeight: 510, fontSize: 15.5 }}>Couldn&apos;t load that brief</p>
              <p style={{ color: 'var(--ink-2)', marginTop: 8, fontSize: 13.5 }}>{state.error.message}</p>
            </div>
          </div>
        )}

        {state.status === 'ready' && (
          <>
            <Pills
              brief={{
                niche: state.data.niche,
                platform: state.data.platform,
                audience: state.data.audience,
                objectives: [state.data.goal],
              }}
              left
            />
            <div className="resultbar no-print">
              <Link className="btn-ghost" to="/dashboard">← Back to dashboard</Link>
              <button className="btn-dark" type="button" onClick={() => window.print()}>Download as PDF ⭳</button>
            </div>
            <BriefContent data={state.data.brief} niche={state.data.niche} />
          </>
        )}
      </div>
    </>
  )
}
